Vagrant.configure("2") do |config|
  config.vm.define "ubMaster" do |ubMaster|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.gui=false
    end
    ubMaster.vm.box = "ubuntu/bionic64"
    ubMaster.vm.define "ubMasterAnsibleCruise"
    ubMaster.vm.provision "file",
        source: "jenkins.minedy.by",
        destination: "/home/vagrant/jenkins.minedy.by"
    ubMaster.vm.provision :shell, :path => "bootstrap.sh"
    ubMaster.vm.network "public_network", ip: "192.168.222.200",  bridge: "eno1"
  end
  config.vm.define "ubSlave" do |ubSlave|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui=false
    end
    ubSlave.vm.box = "ubuntu/bionic64"
    ubSlave.vm.define "ubSlaveAnsibleCruise"
    ubSlave.vm.provision :shell, :path => "bootstrap_slave.sh"
    ubSlave.vm.network "public_network", ip: "192.168.222.201",  bridge: "eno1"
  end
  config.vm.define "centos" do |centos|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui=false
    end
    centos.vm.box = "bento/centos-7.5"
    centos.vm.define "centosAnsibleCruise"
    centos.vm.network "public_network", ip: "192.168.222.202",  bridge: "eno1"
  end
end
