{
 "title": "HW-16 Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "TimeGap", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Running Pods & Containers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": " sum(kubelet_running_pods)", "legendFormat": "Running Pods" },
    {
     "expr": "sum(kubelet_running_containers)",
     "legendFormat": "Running Containers"
    }
   ]
  },
  {
   "title": "JenkinsLogs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate({container=\"jenkins\", namespace=\"ci-cd\"} [$TimeGap]))",
     "legendFormat": "Log"
    }
   ]
  },
  {
   "title": "Jenkins ErrorLogs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate({container=\"jenkins\", namespace=\"ci-cd\"} |~ `\\b(?:WARNING|ERROR)\\b` [$TimeGap]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "MasterNode Err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate({app=\"master1\"} |= `error` [$TimeGap]))",
     "legendFormat": "err"
    }
   ]
  },
  {
   "title": "Ingress ErrorLogs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"ingress-nginx\", app=\"ingress-nginx\"} |= `error` [$TimeGap]))",
     "legendFormat": "Error"
    }
   ]
  }
 ]
}