{
 "title": "Count of Warnings",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "5m, 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Jenkins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({app=\"jenkins-app\"} |= \"INFO\"[$interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({app=\"ingress-nginx\"} |= \"INFO\"[$interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({app=\"node-exporter\"} |= \"info\"[$interval])",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}