---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: ci-cd
type: Opaque
stringData:
  admin-password: <>
  github-token: <>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: ci-cd
data:
  jenkins.yaml: |
    jenkins:
      numExecutors: 2
      clouds:
        - kubernetes:
            containerCapStr: "10"
            maxRequestsPerHostStr: "32"
            jenkinsUrl: "http://jenkins.ci-cd.svc.cluster.local:8080"
            name: "kubernetes"
            namespace: "ci-cd"
            skipTlsVerify: true
    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  description: "GitHub user"
                  id: "github-creds"
                  scope: GLOBAL
                  username: "CHANGE_ME"
                  password: "${GITHUB_TOKEN}"
    unclassified:
      location:
        adminAddress: "CHANGE_ME@example.com"
        url: "http://jenkins.k8s-9.sa/"
      shell:
        shell: "/bin/bash"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-security
  namespace: ci-cd
data:
  basic-security.groovy: |
    #!groovy
    import jenkins.model.*
    import hudson.security.*
    def instance = Jenkins.getInstance()
    println "--> creating local user 'admin'"
    def password = System.getenv("ADMIN_PASSWORD")
    def hudsonRealm = new HudsonPrivateSecurityRealm(false)
    hudsonRealm.createAccount('admin', password)
    instance.setSecurityRealm(hudsonRealm)
    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    strategy.setAllowAnonymousRead(false)
    instance.setAuthorizationStrategy(strategy)
    instance.save()
