{
 "title": "16.Logging",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Time", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ingress-errors",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"ingress-nginx\", container=\"controller\"} |= `error` [$__interval]))"
    }
   ]
  },
  {
   "title": "loki-errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"monitoring\", container=\"loki\"} |= `error` [$__interval]))"
    }
   ]
  },
  {
   "title": "Jenkins-errors",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"ci-cd\", container=\"jenkins\"} |= `FAILURE` [$__interval]))"
    }
   ]
  },
  {
   "title": "Wordpress-errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"default\", container=\"wordpress\"} |= `error` [$__interval]))"
    }
   ]
  }
 ]
}