Vagrant.configure("2") do |config|
  config.vm.define "ubuntu20" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu-ansible"
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.network "public_network", ip: "192.168.100.201"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-ansible"
      vb.gui = false
      vb.memory = "1024"
    end
    ubuntu.vm.provision "shell", run: "always", inline: <<-SHELL
        useradd updater -p ansible
        bash -c "echo 'updater ALL=(ALL:ALL) NOPASSWD: ALL'>> /etc/sudoers"
	echo "user has been added"
	apt update && sudo apt upgrade -y
	apt install software-properties-common
	apt-add-repository --yes --update ppa:ansible/ansible
	apt install -y ansible
	ansible --version
	echo "ansible has been installed"
    SHELL
  end
end
