Vagrant.configure("2") do |config|
  config.vm.define "ubuntu20" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.network "public_network", ip: "192.168.100.201"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    ubuntu.vm.provision "shell", run: "always", inline: <<-SHELL
        sudo useradd updater -p ansible
        sudo bash -c "echo 'updater ALL=(ALL:ALL) NOPASSWD: ALL'>> /etc/sudoers"
	echo "user has been added"
	sudo apt update && sudo apt upgrade -y
	sudo apt install software-properties-common
	sudo apt-add-repository --yes --update ppa:ansible/ansible
	sudo apt install -y ansible
	ansible --version
	echo "ansible has been installed"
    SHELL
  end
end
