Vagrant.configure("2") do |config|
  config.vm.define "Jenkins"
  config.vm.box = "centos/7"
  config.vm.network "public_network", ip: "192.168.100.101", bridge: "enp3s0"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "play.yaml"
  end

end
