
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "centos"
    config.vm.provision "shell", inline: <<-SHELL
       sudo yum -y install git vim wget curl
       echo "vagrant:vagrant" |sudo chpasswd -e
   SHELL
end
