{
 "title": "17.HW_Jenkins_Ingress_Nodeexporter_WP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": "1m, 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Jenkins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"jenkins-6b89844bd5-sdcq7\"}"
    }
   ]
  },
  {
   "title": "Wordpress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"sa-wordpress-7cd777c566-ff77h\"} |= \"404\" [$__interval])"
    }
   ]
  },
  {
   "title": "Node-exporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"node-exporter-mcrnw\"} |= `error` [$__interval])"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-7578879f9f-dmgsn\"} |= `error` [$__interval])"
    }
   ]
  }
 ]
}