Vagrant.configure("2") do |config|
  config.vm.define "host1" do |debian|
    debian.vm.box = "debian/bullseye64"
    debian.vm.network "forwarded_port", guest: 80, host: 8083
    debian.vm.network "public_network", ip: "192.168.0.51", bridge: "Intel(R) Ethernet Connection (2) I218-V"
    debian.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "2048"
       vb.cpus = "2"
    end
    debian.vm.provision "shell", inline: <<-SHELL
       sudo -i
       apt-get update && apt-get upgrade -yqq   
       apt-get install -y vim git wget curl nginx
       systemctl enable nginx
       systemctl start nginx
    SHELL
    debian.vm.provision "file", source: "index.html", destination: "/tmp/"
    debian.vm.provision "shell", inline: <<-SHELL
       sudo -i 
       cp /tmp/index.html /var/www/html/index.html
       systemctl restart nginx
       rm -rf /var/lib/apt/lists/*  /tmp/*  /var/tmp/* /usr/share/man /usr/share/doc /usr/share/doc-base
       cat /dev/null > ~/.bash_history && history -c && exit
    SHELL
  end
  config.vm.define "host2" do |centos|
    centos.vm.box = "centos/8"
    centos.vm.network "forwarded_port", guest: 80, host: 8084
    centos.vm.network "public_network", ip: "192.168.0.52", bridge: "Intel(R) Ethernet Connection (2) I218-V"
    centos.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "2048"
       vb.cpus = "2"
    end
    centos.vm.provision "shell", inline: <<-SHELL
       sudo -i
       sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
       sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
       yum update -y
       yum install -y vim git wget curl nginx
       systemctl enable nginx
       systemctl start nginx
    SHELL
    centos.vm.provision "file", source: "index.html", destination: "/tmp/"
    centos.vm.provision "shell", inline: <<-SHELL
       sudo -i 
       cp /tmp/index.html /usr/share/nginx/html/index.html
       systemctl restart nginx
       rm -rf /var/lib/apt/lists/*  /tmp/*  /var/tmp/* /usr/share/man /usr/share/doc /usr/share/doc-base
       cat /dev/null > ~/.bash_history && history -c && exit
    SHELL
  end
end