Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
    config.vm.define "node_01"
    config.vm.network "public_network", ip: "192.168.1.201",  bridge: "enp2s0" 
    config.vm.provision :shell, :path => "bootstrap.sh"
end
