apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jenkins-homework.fullname" . }}
  labels:
    {{- include "jenkins-homework.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jenkins-homework.fullname" . }}
  labels:
    {{- include "jenkins-homework.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jenkins-homework.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jenkins-homework.fullname" . }}
