#!/bin/bash
 
 cd /c/project/sa.it-academy/alex_kolyago
 
 for repos in $(git remote); do
    if [["$n" == *"origin"*]]; then
        date >> log.log
        git push -u $n --all
        echo "push in $n" >> log.log
    fi
    done