pipeline {
    agent {
    	label 'node2'
    }
    environment {
        NEW_BRANCH = "new_branch"
    }
    triggers{ 
        cron('00 02 * * 0') 
    }
        
    stages {
        stage('Clone repository') { 
            steps { 
                    deleteDir()
                    git url: 'git@github.com:morozandralek/ci_cd-home_task.git'
            }
        }
        stage('Config git && Create new branch') { 
            steps { 
                    sh """
                        git config user.email "morozandralek@gmail.com"
                        git config user.name "Andrey Moroz"
                        git config --global push.default simple
                        git checkout -b $NEW_BRANCH
                    """
            }
        }
        stage('Install nmap && check online hosts'){
        	steps {
        	        sh """
        				sudo yum install -y nmap
        				sudo nmap -sn -n 192.168.56.0/24 > nmap_online_hosts
                        date >> nmap_online_hosts
        			"""
        	}
        }
        stage('Install speedtest'){
        	steps {
        			sh """
        				sudo yum -y install wget
        				wget https://bintray.com/ookla/rhel/rpm -O bintray-ookla-rhel.repo
        				sudo mv bintray-ookla-rhel.repo /etc/yum.repos.d/
        				sudo yum -y install speedtest
        			"""
        	}
        }
        stage('Check speedtest'){
        	steps {
        			sh """
        			speedtest --accept-license > check_speedtest
                    date >> check_speedtest
        			"""
        	}
        }
        stage('Git push'){
        	steps {
        	        sh """
        				git add --all
        				git commit -m "Push in repo"
        				git push -u -f origin $NEW_BRANCH
        			"""
        	}
        }
    }
    post {
            success {
                slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
            failure {
                slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
        }
}
