Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "victor"
    config.vm.network "public_network", ip: "192.168.56.110",  bridge: "eth1"
   config.vm.provision "file", source: "~/10.jenkins/jenkins_nginx.conf", destination: "/tmp/jenkins_nginx.conf"
    config.vm.provision :shell, :path => "bootstrap.sh"  
end
