# Параметры авторизации Drupal
drupalUsername: admin
drupalPassword: DrupalAdminPassword555
drupalSecretName: drupal-passwords-v2
drupalSecretPasswordKey: drupal-password

# Использование существующего секрета для самого Drupal
auth:
  existingSecret: drupal-passwords-v2
  passwordKey: drupal-password

# Включаем Istio обратно, но заставляем приложение ждать готовности сети
podAnnotations:
  proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

# Глобальные настройки репозиториев
global:
  imageRegistry: docker.io
  security:
    allowInsecureImages: true

# Конфигурация основного приложения Drupal
image:
  registry: docker.io
  repository: bitnamilegacy/drupal
  tag: 11.2.3-debian-12-r1

# Отключение постоянных томов (Persistence)
persistence:
  enabled: false

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/os-shell

# Сетевые настройки сервиса в K8s
service:
  type: ClusterIP
  ports:
    http: 8080 # Явно указываем стандартный порт контейнера Bitnami

# Конфигурация встроенной базы данных MariaDB
mariadb:
  auth:
    existingSecret: drupal-passwords-v2
    # Cтандартные ключи внутри секретов
    passwordKey: mariadb-password
    rootPasswordKey: mariadb-root-password
  primary:
    podAnnotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    persistence:
      enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
    tag: 12.0.2-debian-12-r0
  osShell:
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell
  volumePermissions:
    enabled: false
