Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.200",  bridge: "wlo1" ## TO CHANGE
    config.vm.provision :shell, :path => "bootstrap.sh"
end
