# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "elegoev/ubuntu-18.04-jenkins"
    config.vm.define "jenkins" do |machine|
        machine.vm.network "public_network", ip: "192.168.113.106", brige: "eno1"
        machine.vm.network "forwarded_port", guest: 8080, host: 8888
	machine.vm.provision "shell", inline: "echo ubuntu:ubuntu | chpasswd"
	machine.vm.provision "shell", inline: "apt-get update && apt-get install -y python-minimal"
     ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
       config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
       config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
       config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
       config.vm.provision :shell, :path => "bootstrap.sh"
  end
end
