$master_pub_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5ucQRZSj6InBD6Pob2CaIKSgxNOALd8FeaSwgjuslhRx6VzX6AYEEdRLP5sNULaERHjgozxh5/h0edBGM7qsacA/luZVrOnOIfaUVTp+5xlghK02895cE5jXoEiqjmiGtZQU3AHB6PBihi0QhtIipP/cqmFB62G1rPx0Sb79BqGp6KPE1gIUSqhj7IwI/TcLdV1cUH4npLEa8/nyzdGPz8O1bjTXHKERGg2inTGs8wmyrUibGUxauqpH4JImyrrPObyInPMocggtiQWHoevmGMdBUggUh7W8QtztcZFup2c9zsbGXz58znHgA0IbOWdpoK9o5756IcbCwZA5t/WYh jenkins@localhost.localdomain1"
$script = <<-SCRIPT
yum -y install java-1.8.0-openjdk git -q
useradd -d /var/lib/jenkins jenkins
sudo runuser -l jenkins -c 'echo -e "\n\n\n" | ssh-keygen -t rsa'
sudo runuser -l jenkins -c 'cat /tmp/authorized_keys >> /var/lib/jenkins/.ssh/authorized_keys'
chown jenkins:jenkins /var/lib/jenkins/.ssh/authorized_keys 
chmod 600 /var/lib/jenkins/.ssh/authorized_keys
rm -f /tmp/authorized_keys
echo "Client done!"
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "Jenkins_node"
	config.vm.network "private_network", ip: "10.0.0.11"
	config.vm.provision "file", 
		source: "authorized_keys", 
		destination: "/tmp/authorized_keys"
	config.vm.provision "shell",
		inline: $script
end
