Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.3",  bridge: "Intel(R) Ethernet Connection (2) I219-V"
    config.vm.provision :shell, :path => "nginx.sh"
    config.vm.provision :shell, :path => "bootstrap.sh"
end
