Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"
  config.vm.network "public_network", ip: "192.168.100.11", guest: 80, host: 8081
  config.vm.provider "virtualbox" do |v|
	v.memory = 512
    v.cpus = 1
  end
  
  config.vm.provision "shell", inline: <<-SHELL
  yum install -y vim git wget curl
  useradd -p vagrant -s /bin/bash updater
  sudo bash -c 'echo "updater ALL=(ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'
  SHELL
 
end