```bash
    pipeline { 
    agent {label '!master'}
    triggers {
        cron('0 2 * * 7')
    }
    stages {
        stage('Check online hosts via nmap') { 
            steps { 
                sh '''
                  sudo apt update 
                  sudo apt install nmap 
                  sudo nmap -sP 10.50.28.0/24 | sed '/MAC/d' >> ip_speed
                  sudo apt remove -y nmap
                '''
            }
        }
        stage('Check Internet speed by Speedtest-cli') {
            steps { 
                sh '''
                  sudo apt-get install gnupg1 apt-transport-https dirmngr
                  export INSTALL_KEY=379CE192D401AB61
                  export DEB_DISTRO=$(lsb_release -sc)
                  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY
                  echo "deb https://ookla.bintray.com/debian ${DEB_DISTRO} main" | sudo tee  /etc/apt/sources.list.d/speedtest.list
                  sudo apt-get update
                  sudo apt-get install speedtest
                  speedtest >> ip_speed
                  sudo apt-get remove -y speedtest
                  cat ip_speed
                '''
            }
        }
        stage('Push file to the GitHub') {
          steps {
            sh '''
              sudo mkdir git
              sudo cp ip_speed git/ip_speed
              sudo rm ip_speed
              git init
              git config --global user.email "vp@test.com"
              git config --global user.name "Valery Piotuh"
              git add --all
              git commit -m "Autopush from Jenkins"
              #git remote add origin2 https://vaaleraa:ksok15mv!@github.com/vaaleraa/jenkins.git
              git push origin2 master
              sudo rm -rf git
            '''
          }
        }
       }
    }
```
