Vagrant.configure("2") do |config|

	config.vm.box = "generic/ubuntu1804"
	
	config.vm.define "lab-jenkins01"
	config.vm.hostname = "lab-jenkins01"
	config.vm.network "public_network", ip: "192.168.1.203"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "lab-jenkins01"
		vb.gui = false
		vb.memory = "4096"
		vb.cpus = "4"
		vb.customize ["modifyvm", :id, "--ioapic", "on"]
	end

	if Vagrant.has_plugin?("vagrant-timezone")
		config.timezone.value = "Europe/Minsk"
	end
          
	config.vm.provision "shell", path: "bootstrap.sh"
        
	config.vm.provision "ansible_local" do |ansible|
        config.vm.synced_folder ".", "/vagrant"
		ansible.playbook = "./play.yml" 
		ansible.become = true
        end
        
end