Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.100", bridge: "Intel(R) Ethernet Connection (7) I219-V"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end
    config.vm.provision :shell, :path => "bootstrap.sh"
end
