pipeline {
    agent { 
        label 'ansi1'
    }
    environment {
        NEW_BRANCH = "branch_j1"
		SOURCE_BRANCH = "m-sa2-09-19"
		EMAIL = "y.whitest@gmail.com"
		NAME = "Yury Kazakevich"
    }
    stages {
        stage('Clone repository') { 
            steps { 
                    deleteDir()
                    git url: 'git@github.com:wh1test/sa.it-academy.by.git',
					branch: "${env.SOURCE_BRANCH}"
            }
        }
        stage('Create new branch') { 
            steps { 
                    sh """
						git config user.email $EMAIL
						git config user.name $NAME
                        git checkout -b $NEW_BRANCH
                        git branch
                        git push origin $NEW_BRANCH
                    """
            }
        }
        
        stage('Create file and add content there') { 
            steps { 
                    sh 'touch file.txt'
					sh 'git branch -a > file.txt'
                    sh "ls -l >> file.txt"
					sh 'tar -cvzf file.tar.gz file.txt'
            }
        }
        stage('Push changes') { 
            steps { 
                sh 'git add --all'
                sh '''
                    git commit -m "Added files"
                   '''
                sh 'git push -f origin $NEW_BRANCH'
            }

        }
        stage('Delete branch') { 
            steps { 
                    sh 'git checkout master && git branch -D $NEW_BRANCH'
                    sh 'git push origin --delete $NEW_BRANCH'
            }
        }
        stage('Test') { 
            steps { 
                    sh 'echo "Remote branches are:"'
                    sh 'git branch -r'
                    sh 'echo "Local branches are:"'
                    sh 'git branch'
            }
        }
    }
    post {
            success {
                slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
            failure {
                slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
        }
}