$script = <<-SCRIPT
yum -y 
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins_node"
    config.vm.network "public_network", ip: "192.168.1.201",  bridge: "em1"
    config.vm.provision "file", 
        source: "file.txt", 
        destination: "/tmp/file.txt"
    config.vm.provision "shell", 
        inline: $script
end
###############################################

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.1.200",  bridge: "em1"
    config.vm.provision :shell, :path => "bootstrap.sh"
end
#######################################
$instance_name_prefix = "k8s"
$vm_gui = false

MACHINES = {
  'master' =>  { vcpu: '2', ram: '2048', ip: '192.168.2.156', ssh_port: '33100', size: '10240', file: "data_master.vdi"},
  'node1' =>   { vcpu: '2', ram: '2048', ip: '192.168.2.171', ssh_port: '33101', size: '10240', file: "data_node1.vdi"},
  'node2' =>   { vcpu: '2', ram: '2048', ip: '192.168.2.172', ssh_port: '33102', size: '10240', file: "data_node2.vdi"},
  'etcd' =>    { vcpu: '1', ram: '1024', ip: '192.168.2.157', ssh_port: '33401', size: '10240', file: "data_nfs1.vdi"},
}

INSTANCES = MACHINES.flat_map do |server_name, server|
  server.merge({
    :vagrant_name => "#{server_name}",
  })
end

Vagrant.configure("2") do |vagrant|
  vagrant.ssh.insert_key = false
  INSTANCES.each do |instance|
    vagrant.vm.define instance[:vagrant_name], autostart: false do |machine|
      machine.vm.box = "bento/ubuntu-16.04"
      machine.vm.network "private_network", ip: instance[:ip]
      machine.vm.network "forwarded_port", guest: 22, host: instance[:ssh_port]
      machine.vm.provider "virtualbox" do |vb|
        vb.gui = $vm_gui
        vb.memory =  instance[:ram]
        vb.cpus = instance[:vcpu]
        if !File.exist?(instance[:file])
            vb.customize ['createhd', '--filename',instance[:file], '--variant', 'Fixed', '--size',  instance[:size]]
        end
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', instance[:file]]
      end
      machine.vm.provision 'Start installation', type: 'shell' do |install|
        install.inline = 'sudo swapoff -a'
      end
    end
  end
end
