$script = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
apt-get update 
apt-get install -yqq vim mc net-tools
cat /tmp/pub_key.pub >> /home/vagrant/.ssh/authorized_keys
chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
chmod 600 /home/vagrant/.ssh/authorized_keys
SCRIPT

PUB_KEY_PATH = "~/.ssh/id_rsa.pub"

MACHINES = {
  'host1'  =>  { vcpu: '1', ram: '512', ip: '10.20.30.20'},
  'host2' =>  { vcpu: '1', ram: '512', ip: '10.20.30.21'},
  'jump' =>  { vcpu: '1', ram: '512', ip: '10.20.30.22'},
}

INSTANCES = MACHINES.flat_map do |server_name, server|
    server.merge({
      :vagrant_name => "#{server_name}",
    })
end

Vagrant.configure("2") do |config|
  INSTANCES.each do |instance|
    config.vm.define instance[:vagrant_name] do |node|
      node.vm.box = "bento/debian-10"
      node.vm.hostname = instance[:vagrant_name]
      node.vm.network "private_network", ip: instance[:ip]
      if instance[:vagrant_name] == "jump"
        node.vm.network "public_network", ip: "192.168.1.50", bridge: "wlp2s0"
      end
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = instance[:ram]
        vb.cpus = instance[:vcpu]
      end
      node.vm.provision "file", source: PUB_KEY_PATH, destination: "/tmp/pub_key.pub"
      node.vm.provision "shell", inline: $script
    end
  end
end