Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/pub_key.pub"
  config.vm.provision "shell", inline: <<-COMMON
    sudo useradd -m ansible
    sudo echo "ansible:ansible" | chpasswd
    sudo echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    echo "user ansible registred as sudo user"
    mkdir /home/ansible/.ssh
    touch /home/ansible/.ssh/authorized_keys
    mv /tmp/pub_key.pub /home/ansible/.ssh/authorized_keys
    chown -R ansible:ansible /home/ansible/.ssh/authorized_keys
    chmod 600 /home/ansible/.ssh/authorized_keys
    echo "ssh key add success" 
  COMMON
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/pub_key.pub"
  #jump machine 
  config.vm.define "jump" do |jump|
    jump.vm.box = "centos/7" 
    jump.vm.network "public_network", ip: "192.168.22.221", bridge: "ens32"
    jump.vm.network "private_network", ip: "10.20.30.40"
    jump.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
  end 
  #debian machine 
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/contrib-jessie64"
    debian.vm.network "private_network", ip: "10.20.30.41"
    debian.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
  end
  #centos machine 
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network "private_network", ip: "10.20.30.42"
    centos.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
  end 
end
