# Generated by Django 3.0.4 on 2020-04-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20200402_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='email_address',
            new_name='email',
        ),
    ]
