# Generated by Django 3.0.4 on 2020-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200402_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
