# Generated by Django 3.0.4 on 2020-04-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_auto_20200402_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
