# Generated by Django 3.0.4 on 2020-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_auto_20200404_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('S', 'Senior')], default='J', max_length=1),
            preserve_default=False,
        ),
    ]
