{
 "title": "17.Log monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": "5m, 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "alertmanager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"alertmanager-58fc6c868f-qb24p\"}[$__interval] |=\"error\")"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-7578879f9f-7jwfd\"}[$__interval] |=\"error\")"
    }
   ]
  },
  {
   "title": "wordpress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"sa-wordpress-747b88b85b-nn2lj\"}[$__interval] |=\"error\")"
    }
   ]
  },
  {
   "title": "jenkins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-849959945d-wgwcm\"}[5d] |=\"error\")"
    }
   ]
  }
 ]
}