Vagrant.configure("2") do |config|
  config.vm.define "host1" do |debian|
    debian.vm.box = "generic/debian10"
    debian.vm.network "private_network", ip: "192.168.56.101"
    debian.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    debian.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y vim git wget curl
    SHELL
  end
  config.vm.define "host2" do |centos|
    centos.vm.box = "generic/centos8"
    centos.vm.network "private_network", ip: "192.168.56.102"
    centos.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    centos.vm.provision "shell", inline: <<-SHELL
      yum install -y vim git wget curl
    SHELL
  end
end
