apiVersion: v1 # Версия API Kubernetes для базовых объектов
kind: Namespace # Тип создаваемого ресурса — пространство имен для изоляции проекта
metadata: # Метаданные объекта
  name: {{ .Values.namespace.name }} # Динамическое имя пространства имен из values.yaml
  labels: # Метки (теги) для объекта
    istio-injection: {{ .Values.namespace.istioInjection | quote }} # Подстановка метки Istio
