apiVersion: v1
kind: Secret # Объект Kubernetes для безопасного хранения паролей и токенов
metadata:
  name: jenkins-secret # Фиксированное имя секретного объекта
  namespace: {{ .Values.namespace.name }} # Пространство имен
type: Opaque # Стандартный тип секрета
stringData: # Удобный формат записи (K8s сам закодирует эти строки в формат Base64)
  admin-password: {{ .Values.secrets.adminPassword | quote }} # Подстановка пароля админа в кавычках
  github-token: {{ .Values.secrets.githubToken | quote }} # Подстановка токена гитхаба в кавычках
---
apiVersion: v1 # Версия API для хранения несекретных конфигураций
kind: ConfigMap # Хранилище настроек приложения в текстовом виде
metadata:
  name: jenkins-config # Имя конфигмапа для конфигурации Jenkins как код (JCasC)
  namespace: {{ .Values.namespace.name }}
data: # Блок с конфигурационными файлами
  jenkins.yaml: | # Объявление файла настроек Jenkins
    jenkins: # Корневой раздел настроек Jenkins
      numExecutors: {{ .Values.casc.numExecutors }} # Подстановка количества локальных воркеров
      clouds: # Настройка интеграции с облачными провайдерами ресурсов
        - kubernetes: # Подключение плагина Kubernetes для динамических агентов
            containerCapStr: {{ .Values.casc.containerCapStr | quote }} # Лимит на общее число контейнеров-агентов
            maxRequestsPerHostStr: {{ .Values.casc.maxRequestsPerHostStr | quote }} # Лимит одновременных запросов к API
            jenkinsUrl: "http://jenkins.{{ .Values.namespace.name }}.svc.cluster.local:8080" # Внутренний DNS-адрес мастера для агентов
            name: "kubernetes" # Системное имя облака в настройках Jenkins
            namespace: {{ .Values.namespace.name | quote }} # Пространство имен, где Jenkins будет создавать поды-агенты
            skipTlsVerify: true # Отключение проверки SSL-сертификатов внутреннего API Kubernetes
    credentials: # Раздел автоматического создания учетных данных (доступов)
      system: # Системная область видимости
        domainCredentials: # Доменная область
          - credentials: # Список доступов
              - usernamePassword: # Создание пары Логин/Пароль
                  description: "GitHub user" # Описание кредов в веб-интерфейсе
                  id: "github-creds" # Уникальный ID учетных данных для использования в пайплайнах
                  scope: GLOBAL # Доступность во всех проектах
                  username: {{ .Values.casc.domainUsername | quote }} # Переменная для логина пользователя GitHub
                  password: "${GITHUB_TOKEN}" # Ссылка на переменную окружения ОС (подставится из секрета при старте)
    unclassified: # Прочие глобальные системные настройки Jenkins
      location: # Настройка адресации системы
        adminAddress: {{ .Values.casc.adminAddress | quote }} # Почта отправителя уведомлений
        url: "http://{{ .Values.ingress.host }}/" # Глобальный внешний URL-адрес вашего Jenkins для генерации ссылок
      shell: # Настройка командной оболочки по умолчанию
        shell: "/bin/bash" # Использовать полноценный bash вместо дефолтного sh внутри скриптов сборки
---
apiVersion: v1 # Версия API
kind: ConfigMap # Конфигмап для скриптов первоначальной автоматической инициализации Jenkins
metadata:
  name: basic-security # Имя конфигмапа безопасности
  namespace: {{ .Values.namespace.name }}
data:
  basic-security.groovy: | # Groovy-скрипт, который выполнится при старте системы
    #!groovy
    import jenkins.model.*
    import hudson.security.*
    def instance = Jenkins.getInstance() # Получение текущего запущенного инстанса Jenkins
    println "--> creating local user 'admin'" # Вывод лога в консоль контейнера
    def password = System.getenv("ADMIN_PASSWORD") # Считывание пароля админа из переменных окружения
    def hudsonRealm = new HudsonPrivateSecurityRealm(false) # Инициализация встроенной базы пользователей Jenkins
    hudsonRealm.createAccount('admin', password) # Создание учетной записи админа с паролем из секрета
    instance.setSecurityRealm(hudsonRealm) # Активация базы пользователей в системе
    def strategy = new FullControlOnceLoggedInAuthorizationStrategy() # Создание стратегии "Полный доступ всем вошедшим"
    strategy.setAllowAnonymousRead(false) # Запрет анонимным (неавторизованным) пользователям видеть интерфейс
    instance.setAuthorizationStrategy(strategy) # Применение стратегии безопасности
    instance.save() # Сохранение внесенных изменений на постоянный диск
