apiVersion: v1 # Версия API для базовых абстракций сети
kind: Service # Сетевая абстракция (балансировщик) для объединения подов под стабильным IP
metadata:
  name: jenkins # Стабильное имя сетевой службы (DNS-имя внутри кластера)
  namespace: {{ .Values.namespace.name }} # Пространство имен службы
spec:
  selector: # Маршрутизация трафика на правильные поды
    app: jenkins # Перенаправлять входящие пакеты на поды, у которых есть метка app=jenkins
  ports: # Список открываемых службой сетевых портов
    - name: http # Имя порта для веб-трафика
      port: 8080 # Внешний порт самой службы Service
      targetPort: 8080 # Порт внутри контейнера пода, куда нужно перенаправить пакет
    - name: jnlp # Имя порта для взаимодействия с агентами
      port: 50000 # Порт службы Service
      targetPort: 50000 # Целевой порт связи агента с мастером внутри контейнера
