
$script = <<-SCRIPT
useradd -m -p vagrant updater
echo "updater ALL=(ALL:ALL) NOPASSWD: ALL">>/etc/sudoers
apt-get update -y
apt install -y vim git wget curl
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = "256"
          vb.name = "debian10"
  end
  config.vm.provision "shell", inline: $script
end
