Vagrant.configure("2") do |config|
config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"

  
    config.ssh.insert_key = true
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443
    config.vm.network "forwarded_port", guest: 8001, host: 8001
    config.vm.network "forwarded_port", guest: 30000, host: 30001
  
  config.vm.define "web2" do |web2|
    web2.vm.box = "bento/ubuntu-16.04"
    web2.vm.hostname = "app2"
    web2.vm.network "public_network", ip: "192.168.1.36",  bridge: "wlp2s0"
    web2.vm.provider "virtualbox" do |v|
      v.name = "app2"
      v.memory = 1024
      v.cpus   = 1
      v.gui = false
    end

  end

end
