Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "172.16.0.109",  bridge: "ens192" ## TO CHANGE
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 80, host: 8081
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "play.yaml"
    end
end

