{
 "title": "HW_log_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_range", "label": "Time  range", "query": "5m, 1h, 1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-84b85b6b66-nklhw\"}[$time_range]|=\"error\")"
    }
   ]
  },
  {
   "title": "jenkins",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-helm-697dcd7495-b28fc\"}[$time_range]|=\"error\")"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"node-exporter.*\"}[$time_range]|=\"error\")"
    }
   ]
  }
 ]
}