pipeline {
    agent any
    environment {
        BUILD = "${env.BUILD_ID}"
    }
    stages {
        stage('Clone repository') { 
            steps { 
                    git branch: "master", url: "git@github.com:pawelk82/testpipeline.git"            }
        }
        stage('Checking repository'){
            steps { 
                    sh "ls -l"
            }
        }
        stage('Add date file') {
            steps {
                sh '''
                    touch test.file.txt
                    date >> test.file.txt
                '''
            }
        }
        stage('Push changes') { 
            steps {
                sshagent (credentials: ['jenkins-git']) {
                  sh """
                    git add --all
                    git commit -m "Add new files"
                    git push -f origin master
                  """
                }
            }
        }
        stage('Test files') {
            steps {
                sh "ls -l"
            }
        }
    
    }
    post {
            success {
                slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
            failure {
                slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
        }
}


