#config.vm.network "public_network", ip: "192.168.100.8:8080",  bridge: "wlp2s0"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "Jenkins"
  config.vm.network  "forwarded_port", guest: 8080, host: 9898  
  config.vm.provision :shell, :path => "bootstrap.sh"
end
