Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.define "jenkins"
   config.vm.hostname = "jenkins"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "forwarded_port", guest: 8080, host: 7778
  config.vm.network "forwarded_port", guest: 22, host: 3335
  config.vm.network "private_network", ip: "192.168.7.2",
    virtualbox__intnet: "innet-3"

  config.vm.provision "shell", inline: "sleep 10"
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/webjen.yaml"
    end
end

