# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.5"
#  config.vm.box = "bento/ubuntu-18.04"

  config.vm.define "Jenkins"
  config.vm.network "public_network", ip: "10.13.210.56", bridge: "eth1"
  config.vm.provision :file, source: "setup", destination: "~/"
  config.vm.provision "file", source: "setup\\inventory", destination: "~/"

  config.vm.provision "shell", path: "scriptRH.sh"
#  config.vm.provision "shell", path: "scriptDeb.sh"

  config.vm.provision "shell", path: "run.sh"
end
