Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.84:8080",  bridge: "eno1" 
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "play.yaml"
    end
end

