Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.1.200",  bridge: "wlp0s20f3"
	config.vm.provision :shell, :path => "setup.sh"
end