
Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine38"
    config.vm.define "alpine"
    config.vm.provision "shell", inline: <<-SHELL
       apk add git vim wget curl
       echo "vagrant:vagrant" |sudo chpasswd -e
   SHELL
end
