Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.define "jenkins"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "1"
   end
  config.vm.provision :shell, :path => "bootstrap.sh"
end
