# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.hostname = "cent7Jenkins"  
  config.vm.network "public_network", ip: "192.168.1.215"
  config.vm.define "cent7Jenkins"
  config.vm.provision :shell, :path => "bootstrap.sh"
end