pipeline {
    agent { 
        label 'ubuntu'
    }
    environment {
        BUILD = "${env.BUILD_ID}"
    }
    stages {
        stage('Clone repository') { 
            steps { 
                git(
                    url: 'git@github.com:YuliyaHancharenka/sa.it-academy.by.git',
                    credentialsId: '66f6eb3b-3cd3-492c-997b-6579c2ab1049'
                )
            }
        }
        stage('View branches') { 
            steps { 
                    sh 'echo "Remote branches are:"'
                    sh 'git branch -r'
                    sh 'echo "Local branches are:"'
                    sh 'git branch'
            }
        }
        stage('Checking repository'){
            steps { 
                sh "ls -l"
            }
        }
        stage('Test'){
            steps { 
                sh "test -f README.md"
            }
        }
        stage('Building project'){
            steps { 
                sh "echo version=$BUILD > build_info.ini"
            }
        }
        stage('Packing project') {
            steps {
                sh '''
                tar -zcvf /tmp/$BUILD.tar.gz  ./
                '''
                sh "ls -l /tmp/*.tar.gz"
            }
        }
        stage('Clean old one') {
            steps {
                sh '''
                rm /tmp/$BUILD.tar.gz
                '''
            }
        }
    }
    post {
            success {
                slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
            failure {
                slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
        }
}