Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.ssh.insert_key = false
  config.vm.define "minikube" do |kube|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
  end
  config.vm.network "public_network", ip: "192.168.1.201",  bridge: "en0: Wi-Fi"

  config.vm.provision "kubectl", type: "shell",  inline: <<-SCRIPT
echo "Installing kubectl"
apt-get -qq update && apt-get install -qqy apt-transport-https conntrack
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubectl.list
apt-get update -qq
apt-get install -qqy kubectl
SCRIPT


    config.vm.provision "docker", type: "shell", inline: <<-SCRIPT
sudo apt-get remove docker docker-engine docker.io
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
sudo apt-get update -qq
sudo apt-get install -yqq docker-ce
usermod -aG docker vagrant
sudo docker run hello-world
SCRIPT

    config.vm.provision "minikube", type: "shell", inline: <<-SCRIPT
echo "Downloading minikube"
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.21.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin
SCRIPT

    config.vm.provision "k8s", type: "shell", inline: <<-SCRIPT
echo "Setting up and starting K8S"
sudo minikube start --driver none
sudo kubectl cluster-info
sudo kubectl proxy --address='0.0.0.0' --disable-filter=true  &
sudo minikube dashboard --url
SCRIPT
  end

end
