Vagrant.configure("2") do |config|
  config.vm.define "debian-10" do |vm1|
    vm1.vm.hostname = "Debian10"
    vm1.vm.box = "bento/debian-10"
    vm1.vm.network "public_network", ip: "192.168.100.200"
    
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "debian10-vm"
      vb.gui = false
      vb.memory = "1024"
    end

    vm1.vm.provision "shell", run: "always", inline: <<-SHELL
        apt-get install -y vim git wget curl
        sudo useradd updater -p vagrant
        cat /etc/passwd | grep updater 
	sudo bash -c "echo 'updater ALL=(ALL:ALL) NOPASSWD: ALL'>> /etc/sudoers"
	echo "Added user"
	
    SHELL
  end

  config.vm.define "centos-vm" do |vm2|
    vm2.vm.hostname = "centos-vm"
    vm2.vm.box = "bento/centos-8"
    vm2.vm.network "public_network", ip: "192.168.100.201"
    
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "centos-vm"
      vb.gui = false
      vb.memory = "1024"
    end

    vm2.vm.provision "shell", run: "always", inline: <<-SHELL
        yum install -y vim git wget curl
	adduser updater -p vagrant
	echo "updater ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
    SHELL
  end
  
end
