# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "jenkins"
	config.vm.box_check_update = false
	config.vm.network "public_network", bridge: "en1: LAN"
	config.vm.provision 'shell', inline: 'sudo hostname jenkins'
	config.vm.provider :virtualbox do |vb|
		vb.name = "jenkins"		
    end
end
