Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "Jenkins"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.network "public_network",ip: "192.168.100.60" , bridge: "wlp3s0"
  config.vm.provision :file, source: "./config", destination: "/tmp" 
  config.vm.provision :shell, :path => "boot.sh"
end

