Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "private_network", ip: "192.168.57.10"
    config.vm.provision :shell, :path => "bootstrap.sh"
end
