Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", bridge: "wlp2s0", :mac => "0800278F46EC"
  
    config.vm.provision "file", source: "/home/denis7hko/it-academy/Homeworks/Denis_Semashko/10.Jenkins.Start/Jenkins_master/nginx.conf", destination: "/tmp/nginx.conf"
    config.vm.provision "file", source: "/home/denis7hko/it-academy/Homeworks/Denis_Semashko/10.Jenkins.Start/Jenkins_master/jenkins.conf", destination: "/tmp/jenkins.conf"
    config.vm.provision :shell, :path => "bootstrap.sh"
end
