{
 "title": "Log error",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "TimeInterval", "query": "5m,1h,1d" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod!=\"\"}[$TimeInterval] |= \"error\")"
    }
   ]
  },
  {
   "title": "ingress-nginx-controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-6dc865cd86-8mplp\"}[$TimeInterval] |= \"error\")"
    }
   ]
  },
  {
   "title": "Drupal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"my-drupal-5cc7cfff48-sz54m\"}[$TimeInterval] |= \"error\")"
    }
   ]
  },
  {
   "title": "Jenkins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins2-64bfd8ffdd-mgvvb\"}[$TimeInterval] |= \"\")"
    }
   ]
  }
 ]
}