Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.110", bridge: "enp4s0"
    config.vm.provision "file",
        source: "jenkins.conf",
        destination: "/tmp/jenkins.conf"
    config.vm.provision :shell, :path => "bootstrap.sh"
end


