FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY hello.go .

RUN CGO_ENABLED=0 GOOS=linux go build -o hello hello.go

FROM scratch

WORKDIR /app

COPY --from=builder /app/hello .

CMD [ "./hello" ]

