apiVersion: v1
kind: Secret
metadata:
  name: my-jenkins-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://maksimsolapai-gif.github.io/sa-36-26-jenkins/
