apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homework-secrets
  namespace: argocd
spec:
  project: homework-project
  source:
    repoURL: https://github.com/maksimsolapai-gif/argo-flux-36-26.git
    targetRevision: HEAD
    path: apps-data
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
