apiVersion: v1
kind: Namespace
metadata:
  name: drupal
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: drupal-gateway
  namespace: drupal
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: drupal
  namespace: drupal
spec:
  parentRefs:
    - name: drupal-gateway
      namespace: drupal
      sectionName: http

  hostnames:
    - drupal.local

  rules:
    - backendRefs:
        - name: drupal
          port: 80