# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "generic/centos7"


   # disabled check virtualboxguestadditional.iso
   config.vbguest.auto_update = false
   config.vm.network "public_network", ip: "192.168.1.101", bridge: "wlp3s0", type: "dhcp", auto_config: false
 # These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
    vb.gui = false

  # Customize the amount of memory on the VM:
   vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
     yum update
     yum install vim git wget curl -y
     SHELL

end
