$script = <<-SCRIPT
apt-get update
mv /tmp/pub_key.pub /home/vagrant/.ssh/authorized_keys
chown -R vagrant:vagrant /home/vagrant/.ssh/authorized_keys
chmod 600 /home/vagrant/.ssh/authorized_keys
echo "Client done!"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node|
    node.vm.box = "bento/ubuntu-18.04"
    node.vm.define "nodelab"
    node.vm.network "public_network", ip: "192.168.1.55",  bridge: "eno1"
    node.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "512"
    end
    node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/pub_key.pub"
    node.vm.provision "shell", 
        inline: $script
  end
#  config.vm.define "nodeprod" do |nodeprod|
#    nodeprod.vm.box = "bento/ubuntu-18.04"
#    nodeprod.vm.define "nodeprod"
#    nodeprod.vm.network "public_network", ip: "192.168.1.51",  bridge: "eno1"
#    nodeprod.vm.provider "virtualbox" do |vb|
#       vb.gui = false
#       vb.memory = "512"
#    end
#    nodeprod.vm.provision "file", source: "./files", destination: "/tmp"
#    nodeprod.vm.provision "shell",
#        inline: $script
#  end
end
