Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    if Vagrant.has_plugin?("vagrant-vbguest") then
          config.vbguest.auto_update = false
    end
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.1.110", bridge: "wlo1"
    config.vm.provider :virtualbox do |vb|
      vb.memory = "4096"
    end
    config.vm.provision :shell, :path => "bootstrap.sh"
end
