Vagrant.configure(2) do |config|

  config.vm.define "srv1" do |srv1|
  srv1.vm.box = "ubuntu/trusty64"
  srv1.vm.box_check_update = false
  srv1.vm.hostname = "ubuntu"  
  srv1.vm.define "web1"
  srv1.vm.network "public_network", ip: "192.168.88.17", bridge: "enp4s0"
  srv1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  
    config.vm.provider "virtualbox" do |srv1|
      srv1.gui = false
      srv1.memory = "1024"
    end
  end

  config.vm.define "srv2" do |srv2|
  srv2.vm.box = "centos/7"
  srv2.vm.box_check_update = false
  srv2.vm.hostname = "centos"
  srv2.vm.define "web2"
  srv2.vm.network "public_network", ip: "192.168.88.18", bridge: "enp4s0"
  srv2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  
    config.vm.provider "virtualbox" do |srv2|
      srv2.gui = false
      srv2.memory = "1024"
    end
  end
end
