
name: Hello World Workflow


on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  say-hello:                    
    runs-on: ubuntu-latest       
    steps:                       
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   

      - name: Run hello script
        run: python3 hello.py      
