$script = <<-SCRIPT
yum install java wget git -y --nogpgcheck -q
wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
yum install jenkins -y --nogpgcheck -q
## Install docker
curl -fsSL https://get.docker.com/ | sh
systemctl enable docker
systemctl start docker

yum install epel-release -y
yum install nginx -y
systemctl start nginx
systemctl enable nginx
setsebool -P httpd_can_network_connect 1
mv /tmp/jenkins.conf /etc/nginx/conf.d/
systemctl restart nginx

usermod -s /bin/bash jenkins
#sudo firewall-cmd --permanent --service=jenkins --add-port=8080/tcp
#sudo firewall-cmd --reload
usermod -a -G docker jenkins
usermod -aG jenkins nginx
#usermod -aG jenkins www-data
systemctl enable jenkins
systemctl start jenkins
echo "##### Waiting for secret"
while [ ! -f /var/lib/jenkins/secrets/initialAdminPassword ]
do
    sleep 2
done
runuser -l jenkins -c 'echo -e "\n\n\n" | ssh-keygen -t rsa'
runuser -l jenkins -c 'cat ~/.ssh/id_rsa'
runuser -l jenkins -c 'cat ~/.ssh/id_rsa.pub'

echo "##### Secret here"
cat /var/lib/jenkins/secrets/initialAdminPassword
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.99.99", bridge: "Realtek PCIe FE Family Controller", ipv6: "false"
	config.vm.network "forwarded_port", guest: 22, host: 8088
    config.vm.network "private_network", ip: "192.168.49.88"
    config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "512"
	   vb.name = "centos-Jenkins"
    end	
#    config.vm.provision :shell, :path => "bootstrap.sh"
    config.vm.provision "file", 
        source: "jenkins.conf", 
        destination: "/tmp/jenkins.conf"
    config.vm.provision "shell",
        inline: $script
    end