# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "hyperv" do |h|
     h.vmname ="jenkins"
     h.memory = "1024"
  config.vm.provision :shell, :path => "bootstrap.sh"
  end

end