{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "label": "time", "query": "5m, 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "grafana",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"grafana-5f9f96b65b-2n7mf\"}[$time] |= \"error\")"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-7578879f9f-vh76j\"}[$time] |= \"error\")"
    }
   ]
  },
  {
   "title": "ArgoCD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"argocd-server-58b85dcfcc-6lnj8\"}[$time] |= \"error\")"
    }
   ]
  }
 ]
}