Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    # config.vm.network "public_network", ip: "192.168.100.200",  bridge: "en0: Wi-Fi (Wireless)" # config for home Wi-Fi
    config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
    
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "play.yaml"
    end
    
    # # Or use this to install only Jenkins without nginx
    # config.vm.provision :shell, :path => "bootstrap.sh"
end
