pipeline {
    agent any
    environment {
        registry = "kirillpavlov/docker-first"
        registryCredential = 'dockerhub'
    }
    stages {
       stage('Cloning Git') {
            steps {
                git 'git@github.com:pk-active/docker.git'
            }
        }
        stage('Building image') {
            steps {
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
        stage('Deploy Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Remove Unused docker image') {
            steps{
                sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}
