Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.ssh.private_key_path = "~/.ssh/id_rsa"
    config.ssh.forward_agent = true
    config.vm.network "public_network", ip: "192.168.100.33"
    config.vm.provision :shell, :path => "bootstrap.sh"
end
