Vagrant.configure("2") do |config|
    config.vm.define "debian-11" do |debian|
      debian.vm.box = "debian/bullseye64"
      debian.vm.network "private_network", ip: "192.168.56.101"
      debian.vm.provider "virtualbox" do |vb|
         vb.gui = false
         vb.memory = "1024"
         vb.cpus = "2"
      end
      debian.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y vim git wget curl nginx
        cp /vagrant/debian.html /var/www/html/index.html
        systemctl restart nginx

      SHELL
    end
    config.vm.define "centos-8" do |centos|
      centos.vm.box = "centos/8"
      centos.vm.network "private_network", ip: "192.168.56.102"
      centos.vm.provider "virtualbox" do |vb|
         vb.gui = false
         vb.memory = "1024"
         vb.cpus = "2"
      end
      centos.vm.provision "shell", inline: <<-SHELL
        dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos -y
        dnf distro-sync
        dnf install -y vim git wget curl nginx
        cp /vagrant/centos.html /usr/share/nginx/html/index.html 
        systemctl enable nginx
        systemctl start nginx
      SHELL
    end
  end