Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.41",  bridge: "wlxfc7516893760" ## TO CHANGE
    config.vm.provision :shell, :path => "bootstrap.sh"
end