Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "10.20.30.83",  bridge: "Intel(R) Ethernet Connection (11) I219-V"
	config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "3072"
	   vb.cpus = "2"
	config.vm.provision :shell, :path => "bootstrap.sh"
	end
end