---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin
  namespace: jenkins-gitops
spec:
  encryptedData:
    password: AgAC/hDH751K0gTyYJRX94VRPffb2rx3olTSJFn44SuJtFId44eY/FtVG+gNdptZiGlKTmqxfgEvosG/wRWhd+WRB7XiJrKf9Yh39jHTdsBrcapqE4bOIP/VxxD/kO4SnKZLvXs3v/4zpM6JbJ3t17x6rkX1fQ0CO3BpI5Hu+3aP1OnEFGEw+fAU1uMMx1ff5NJ4Q5amntE9iRAm/BK/T+hMmdaCmiE68GMuB0XZ/lXIXfcfqggDfbW+amCyABG8JSyG8fEjqH33TPJzmF69j8HarsQCbV28wYj/dq51sFfy9gE1YnAheMsIOQo396sSiYZ//Y1M61aipzRv7jbYhz1HniU5SaVWgrtvK3ghhPjCkBW/2BGRVVOijUdZaVsAsIsvB33ExcZuuS5q3Z3J6rVyX88YpiQD9mUG2rwhQXz04c6pFs2oD5CoXYBVUb2AfeAIbYncHNKj9FZnb10r+oVQSg6HxEbcl7b3elPF2ULMR330Y2T5uYcBrMackxp92vf/gDWAHzUT1AZXnw72DkBtdNMSzdQoWaoDTPo669KIqCpVJW2KEiXhG5Wix503VdqLin8CdQCwXoLxWyJLC6E50ElNVdbwy3pCnO0eTWYtVd+dGNiQHMP+1ka4N42JtxPU5TnJWSt4+J76DMuXIfnbDtRqr51OljDC4GsbEIth/6hyyMtRPud9ti8OLWVFMmmdo3iJfmHzbE5JJBZR0uyiBLHSqBWQdyCzgp2xqmLFKQ==
  template:
    metadata:
      name: jenkins-admin
      namespace: jenkins-gitops
