{
 "title": "My Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "ubuntu-spectator: ERROR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ubuntu-spectator\"} |= `ERROR` [$time])"
    }
   ]
  },
  {
   "title": "ubuntu-spectator: error counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ubuntu-spectator\"} |= `ERROR` [$time])"
    }
   ]
  },
  {
   "title": "Jenkins: WARNING",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-59c7fc56b8-x2t9h\"} |= `WARNING` [$time])"
    }
   ]
  },
  {
   "title": "Jenkins: warning counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-59c7fc56b8-x2t9h\"} |= `WARNING` [$time])"
    }
   ]
  },
  {
   "title": "Wordpress (log files): GET",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"argo-wordpress-f444845bd-rbq2v\"} |= `GET` [$time])"
    }
   ]
  },
  {
   "title": "Wordpress: GET in Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"argo-wordpress-f444845bd-rbq2v\"} |= `GET` [$time])",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Ingress Nginx: ERROR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"ingress-nginx\"} |= `ERROR` [$time])"
    }
   ]
  },
  {
   "title": "Ingress Nginx: error counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"ingress-nginx\"} |= `ERROR` [$time])"
    }
   ]
  }
 ]
}