Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "private_network", type: "dhcp"
    config.vm.provision :shell, :path => "bootstrap.sh"
end