name: Test calculation

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        run: python -m unittest test_calc.py
