Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 80, host: 80
    #config.vm.network "public_network", ip: "192.168.1.200",  bridge: "en0: Wi-Fi" ## TO CHANGE
    config.vm.provision :shell, :path => "bootstrap.sh"
end
