apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  admin-password: {{ .Values.secret.adminPassword | quote }}
  github-token: {{ .Values.secret.githubToken | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: {{ .Values.global.namespace }}
data:
  jenkins.yaml: |
    jenkins:
      numExecutors: {{ .Values.casc.numExecutors }}
      clouds:
        - kubernetes:
            containerCapStr: {{ .Values.casc.containerCapStr | quote }}
            maxRequestsPerHostStr: {{ .Values.casc.maxRequestsPerHostStr | quote }}
            jenkinsUrl: "http://jenkins.{{ .Values.global.namespace }}.svc.cluster.local:8080"
            name: "kubernetes"
            namespace: {{ .Values.global.namespace | quote }}
            skipTlsVerify: true
    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  description: "GitHub user"
                  id: "github-creds"
                  scope: GLOBAL
                  username: {{ .Values.casc.githubUser | quote }}
                  password: "${GITHUB_TOKEN}"
    unclassified:
      location:
        adminAddress: {{ .Values.casc.adminAddress | quote }}
        url: "http://{{ .Values.routing.host }}/"
      shell:
        shell: "/bin/bash"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-security
  namespace: {{ .Values.global.namespace }}
data:
  basic-security.groovy: |
    #!groovy
    import jenkins.model.*
    import hudson.security.*
    def instance = Jenkins.getInstance()
    println "--> creating local user 'admin'"
    def password = System.getenv("ADMIN_PASSWORD")
    def hudsonRealm = new HudsonPrivateSecurityRealm(false)
    hudsonRealm.createAccount('admin', password)
    instance.setSecurityRealm(hudsonRealm)
    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    strategy.setAllowAnonymousRead(false)
    instance.setAuthorizationStrategy(strategy)
    instance.save()