apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-jenkins-pv
  labels:
    app: jenkins
spec:
  capacity:
    storage: {{ .Values.nfs.storageSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: jenkins-home
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.nfs.storageSize }}