$script = <<-SCRIPT
apt update && apt upgrade -yqq
apt install -yqq openjdk-11-jdk wget git curl
useradd -m -d /var/lib/jenkins jenkins
runuser -l jenkins -c 'mkdir /var/lib/jenkins/.ssh/'
runuser -l jenkins -c 'cat /tmp/authorized_keys >> /var/lib/jenkins/.ssh/authorized_keys'
chown jenkins:jenkins /var/lib/jenkins/.ssh/authorized_keys
chmod 600 /var/lib/jenkins/.ssh/authorized_keys
rm -f /tmp/authorized_keys
echo "Client done!"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.define "Jenkins_node"
    config.vm.network "public_network", ip: "192.168.100.41",  bridge: "Intel(R) Dual Band Wireless-AC 8265" 
    config.vm.provision "file",
        source: "authorized_keys",
        destination: "/tmp/authorized_keys"
    config.vm.provision "shell",
        inline: $script
end