Vagrant.configure("2") do |config|
  config.vm.define "host-centos" do |centos|
    centos.vm.box = "centos/8"
    centos.vm.network "forwarded_port", guest: 80, host: 8089
    centos.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "1024"
    end
    centos.vm.provision "shell", inline: <<-SHELL
      yum update -y
      yum install vim git wget curl nginx -y
      systemctl enable nginx
      systemctl start nginx
      echo "<html><header><title>CentOS :: Custom index.html </title></header><body><center><h1>Host system: $(cat /etc/centos-release)</h1></center></body></html>" > /usr/share/nginx/html/index.html
    SHELL
  end
end
