apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ssh-keys-sealedsecret.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-pdb.yaml
  - nginx-routing.yaml
