Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
# config.vm.network "forwarded_port", guest: 80, host: 8082
  config.vm.network "public_network", ip: "192.168.1.235",  bridge: "br0"
  config.vm.synced_folder ".", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
end
