$script = <<-SCRIPT
yum -y install git vim
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins_node"
    config.vm.network "public_network", ip: "192.168.1.201",  bridge: "br0"
    config.vm.provision "file", 
        source: "file.txt", 
        destination: "/tmp/file.txt"
    config.vm.provision "shell", 
        inline: $script
end
