---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgBXacYG9azz8kUKCEbBymndZc0NFu8h55mS+NRoU9tptDMUh6qC91vZqFmHJzrWdwz2kW/FMMHpLZSJ7Jemto7He4/1QcXrEIfRGgVBKEyfmJhAXzEGFIWoZdOjWKnig8gx+AWB/q/La9jPwvTIPXbCUxQgbN1KBE1imJNXITFXjtmQAtBL8KQptHOHdnYcAR9PdAlRhU7uC+e1yuvnQmZnly1ddQ6z82BHMds67Dsx5n7HwZDU5GuAnxT4KT2082sKFbKykvyKrdjpOsu1plj8JRkXNlTMtFDYLyIIQ4N/V9D3STvzCDaJ+tFBOa3f9vnAEGZAfQBhIqRKE8ytsFrUxPlIPHwwENzfIXB17S2kLxbseOMoptEVJ0pNSZhiwe4XJWbQtIxRAtisyDD4LVVvw3yIrWa3CVbnxRCYL08TzJmfjv4Qo5XEpArbIHrPHaO50xDId/nNqE6o3EPtcQ23/GUCOq4EQ6xCkx2vnM73NCI1OiivhaABgYUQg8vyLvqkZneifrlLfmg4g2XO4z/Spu2BRjkphmZHKUaKAm6oaukdWF5ET95xC8xxH9/DEGtRdPXxTFraMK09j/Y5nKLx8P9Pz6rQ+HWSy71AgfX+pntjhsafAR29w3unpj/sAkihbV4/FG30p7FQWFtX5XNTdpJ9SVZ1qOEU3NWpfdYxwXo/sa0PJAGeRgGztofCKLfpIAXxbj0RXODGoXdmzwXiWwwPHL0aUkK0hIL8sBq9N7vsCgw/li9x+QOqfMITRUbn9FKrJ0WUg8HJ7dk5obE8bldNSbA20RDCNnBoXmxMmoY=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
