---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCH3CDYq4JwNQpSo6jeOmler132Wck5Yzjn2deXARFFB9AXebo7mQ7ggn3c5fM0bgGYz8qxFx3VTRdu/i2LuCPhydJp1Gj8k5pOqGjAEf1RpBzNnJJMPTUjaBXFluw2kDhscS6TrdtPRv78Uji093MeEkD+nBTxS+yy6jOeqzWe63eTWLE4GKoSP0hTRJ4Jw1xe9OuEpyWya+oFtzAxLn1QcnqKZW+RPVSdzNuHED6ju4Vor5sVp9GA3DnovzfjC/RFgYU5ihARH5k177/hCS55NKxQRpwRvhK0biOv7zh9mgK9oSXHUrEn9p8OC/OnFx5k/PD96mXv+nyKFzXGKrIItsO+vNmbTaDCjfTrcI818XD5cuR4F7DR5cq5qXTXqoC8s7ZmaX7Nf22wsEHJHWxhOf0wmnnprSfUaOQ5wcKDkiXq7ly9S3UuY51Lcn+HuSfVTUsAR7SBVDAZpQgGC0DmHUELY2Vr6aNK2gKV7iYVGSeiL5cA/J7w6pHGFICQfDhSryQOElVBHmoAP82sstar9Zcnj9KJt0CpwzCKXiTv9TU6dYd8s1WkzgMIb1eqaokTRK6Di2qv/tF8SfvTNKUT0573dSynoUJ9hoS9ExFSl0QEmvQy7eaDKV8ElMPhGiugYw3fmHySCAxH0WFuLhxqAGgIeGsOO8moTjXzuVfeLinOLu2H7E7aULCF1ldGif6kTc/gPyVKfUqVq9YsOSih9aLFr/hk3C344lwGD9BWpQ==
    admin-user: AgBqnv1/2Uu5QFUjZdDO4cEuhf+KM6aqhqsGKYFQy5rTxA3J2AxjE+ByRE+gBJxXKql9i4spd5sYqKe4RUx91PWn1nMV/ix97RFtT7CHhA/gY1WANkxB/PcxxcN180QWVVlDLWw81YT8X7oS18sUBT2kbb/NqxburLUHUCQJCw5pT6eoS7EQH1ejDjRyy++ybM+34o0/qFd8JzWZ2TRdWPjFJ+mtg6I0Uk7PpkwUFGylxol+u9kKnHpKNwAqf6+AIQ5d5P0lMihYPuIb9hAzapU3DaU5JvuZDiz9O5ssTK4ZxLkPZKVBn0RatWYZcjH2KObwv0IO9JTukxxHdKjNX0RXYA4mD8XJ2wR9/goMHb0m8PVEqfjBnPY4BGOlThutDPx79jvm4PYj0TOpOMPxzdXIpx2phdUPfn0AxEnGPXKjES4f6vk7ebQQXlNob4R3wOa6hqirB9wZkDwPlhOSKdFIaj1YAjoAZn41tdPIIiceQfpbZsn5dpjJnBpnYquLzDGoC3mZ2CA1P24hQYDBP2gwPZb5pn/PjPxfAgkjGq2hDqR+6veRYatx5B4P0yC8HxzqQ0CtU880vN+7nBT7Z6J86EbadNcHA1T5375jh7Q5j70RHbbyHUNVrYPkrtTrOPZ5xZYhsvyIbeEYw0t7b+ShiivPZRwirugOowMNDRqxmiiE+AFa7RB7bH216vGySYiBC6btzQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
