{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "7d, 1d, 1h, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Jenkins error counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time ({pod=~\"myjenkins.*\"} [$interval] |=\"error\")"
    }
   ]
  },
  {
   "title": "Node Exporter error counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time ({pod=~\"node-exporter.*\"} [$interval] |=\"error\")"
    }
   ]
  },
  {
   "title": "NGINX error counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time ({pod=~\"mynginx.*\"} [$interval] |=\"error\")"
    }
   ]
  },
  {
   "title": "My Drupal error counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time ({pod=~\"mydrupal.*\"} [$interval] |=\"error\")"
    }
   ]
  }
 ]
}