apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  admin-password: {{ .Values.credentials.adminPassword | quote }}
  github-token: {{ .Values.credentials.githubToken | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-config
  namespace: {{ .Values.global.namespace }}
data:
  jenkins.yaml: |
    jenkins:
      numExecutors: {{ .Values.jenkins.numExecutors }}
      clouds:
        - kubernetes:
            containerCapStr: "{{ .Values.jenkins.cloud.containerCap }}"
            maxRequestsPerHostStr: "{{ .Values.jenkins.cloud.maxRequestsPerHost }}"
            jenkinsUrl: "http://{{ .Values.fullnameOverride }}.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.service.ports.http }}"
            name: "{{ .Values.jenkins.cloud.name }}"
            namespace: "{{ .Values.global.namespace }}"
            skipTlsVerify: {{ .Values.jenkins.cloud.skipTlsVerify }}
    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  description: "GitHub user"
                  id: "github-creds"
                  scope: GLOBAL
                  username: "{{ .Values.jenkins.githubUsername }}"
                  password: "${GITHUB_TOKEN}"
    unclassified:
      location:
        adminAddress: "{{ .Values.jenkins.adminAddress }}"
        url: "{{ .Values.jenkins.externalUrl }}"
      shell:
        shell: "{{ .Values.jenkins.shell }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-security
  namespace: {{ .Values.global.namespace }}
data:
  basic-security.groovy: |
    #!groovy
    import jenkins.model.*
    import hudson.security.*
    def instance = Jenkins.getInstance()
    println "--> creating local user '{{ .Values.credentials.adminUser }}'"
    def password = System.getenv("ADMIN_PASSWORD")
    def hudsonRealm = new HudsonPrivateSecurityRealm(false)
    hudsonRealm.createAccount('{{ .Values.credentials.adminUser }}', password)
    instance.setSecurityRealm(hudsonRealm)
    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    strategy.setAllowAnonymousRead(false)
    instance.setAuthorizationStrategy(strategy)
    instance.save()
