Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |v|
		v.gui = false
	end
	config.vm.box = "centos/7"
	config.vm.define "Jankins"
	config.vm.network "public_network", ip: "192.168.0.200", bridge: "enp1s0"
	config.vm.provision :shell, :path => "bootstrap.sh"
end
