Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenk"
    config.vm.network "public_network", ip: "192.168.100.12",  bridge: "wlx10feed1e823e"
    config.vm.provision "file", 
        source: "jenk.conf", 
        destination: "/tmp/jenk.conf"
    config.vm.provision :shell, :path => "bootstrap.sh"

end