{
 "title": "error",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "5m, 1h, 1d, 5d" }
  ]
 },
 "panels": [
  {
   "title": "ingress error",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (rate({pod=\"ingress-nginx-controller-7578879f9f-x57f4\"} |= `error` [$__range]))"
    }
   ]
  },
  {
   "title": "jenkins error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate({pod=\"jenkinss-5fdb8c8746-wqcz5\"} != `error` [$__range]))"
    }
   ]
  },
  {
   "title": "node-exporter error",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{pod=~\"node-exporter-gdhgb\"} | __error__=``\r\n"
    }
   ]
  },
  {
   "title": "drypal",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{pod=~\"sa-wordpress-9f87cdf9c-vbthv\"}  | __error__=``"
    }
   ]
  }
 ]
}