{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(node)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{},pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{pod=\"$pod\"},container)"
    }
   },
   { "name": "range", "label": "range", "query": "5m, 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Errors Log count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"jenkins.*\"}[$range] |= \"error\")",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "count_over_time({pod=~\"ingress-nginx-controller.*\"}[$range] |= \"error\")",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "count_over_time({pod=~\"node-exporter.*\"}[$range] |= \"error\")",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "count_over_time({pod=~\"sa-wordpress.*\"}[$range] |= \"error\")",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "CPU by Pods",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{pod!=\"\"}[5m])) by (pod)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory by Pods",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=\"\", container!=\"\"}/1048576) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container=\"$container\"}[5m]) ",
     "legendFormat": "Container usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=\"$pod\",container=\"$container\"}[5m])",
     "legendFormat": "Throttling"
    }
   ]
  },
  {
   "title": "Memory by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"$container\",pod=\"$pod\"} / 1048576",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{container=\"$container\",pod=\"$pod\",resource=\"memory\"}) / 1048576",
     "legendFormat": "Container request"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{pod=\"$pod\",container=\"$container\",resource=\"memory\"}) / 1048576",
     "legendFormat": "Conteiner limit"
    }
   ]
  },
  {
   "title": "Restsrts by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\",job=\"kube-state-metrics\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  }
 ]
}