$master_pub_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDInRipgpD6xoEPS89rxU4TLJ39vjOJA7po68mHUswzJLWA+UWJfO9G4FjmQPOGu1rrLmzzk8C+S9dwmLqGft2zceTn/DaSVvwxUoWJjkQ4ECB16kmtaTQM64NYxnjbR6HY6Qdkk2c5hQInv6Q6rwJaktDkElPrkeM9FtiqjDS8yHEQomFPYO/1tDnI0oIV7JVSztFdUjtakMIgy/BI9ODWzRnt/wRsj9HMrM5cxNuS066MyERdlNuSS1k1WI9v6SvPLKsax7nQPVYUSao4aEiO8LGf4lYxMCbaG1CrpAeZYV3drSU84yevbfYKszWPtnF5K9jXY3OMF0LGNS9prQN3 jenkins@localhost.localdomain"
$script = <<-SCRIPT
yum -y install java-1.8.0-openjdk git -q
useradd -d /var/lib/jenkins jenkins
sudo runuser -l jenkins -c 'echo -e "\n\n\n" | ssh-keygen -t rsa'
sudo runuser -l jenkins -c 'cat /tmp/authorized_keys >> /var/lib/jenkins/.ssh/authorized_keys'
chown jenkins:jenkins /var/lib/jenkins/.ssh/authorized_keys 
chmod 600 /var/lib/jenkins/.ssh/authorized_keys
rm -f /tmp/authorized_keys
echo "Client done!"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins_node"
    config.vm.network "public_network", ip: "192.168.1.201",  bridge: "eno1"
    config.vm.provision "file", 
        source: "authorized_keys", 
        destination: "/tmp/authorized_keys"
    config.vm.provision "shell", 
        inline: $script
end
