{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Drupal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"drupal-5978dfd56c-sdgvj\"} |=`error` [$time])"
    }
   ]
  },
  {
   "title": "Jenkins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-6fdbd74c79-dw85k\"} |=`error` [$time])"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-85c8d9bc95-6sl6m\"} |=`error` [$time])"
    }
   ]
  }
 ]
}