apiVersion: v1
kind: Pod
metadata:
  name: failing-pod
  namespace: homework-17
  labels:
    app: failing-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: node2
  restartPolicy: Always
  containers:
    - name: failing-container
      image: busybox:1.36.1
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          echo "$(date -Iseconds) level=INFO message=application-started"
          echo "$(date -Iseconds) level=ERROR message=simulated-failure exit_code=1"
          sleep 2
          exit 1
      resources:
        requests:
          cpu: 5m
          memory: 4Mi
        limits:
          cpu: 20m
          memory: 16Mi
