{
 "title": "Log_Dashboard",
 "description": "Log_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "label": "time", "query": "5m, 1h, 1d" },
   { "name": "type", "label": "type", "query": "error,warning" }
  ]
 },
 "panels": [
  {
   "title": "JENKINS",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"argo-prod\", container=\"jenkins\"}[$time] |= \"$type\")"
    }
   ]
  },
  {
   "title": "INGRESS",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"ingress-nginx\", container=\"controller\"}[$time] |= \"$type\")"
    }
   ]
  },
  {
   "title": "NODE_EXPORTER",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"monitoring\", container=\"node-exporter\"}[$time] |= \"$type\")"
    }
   ]
  }
 ]
}