Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "private_network", ip: "192.168.101.100" #, bridge: "enp3s0" 
    config.vm.provision :shell, :path => "bootstrap.sh"
end
