apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: {{ .Values.namespace }}
data:
  jenkins.yaml: |
    jenkins:
      numExecutors: 2
      clouds:
      - kubernetes:
          containerCapStr: "10"
          maxRequestsPerHostStr: "32"
          jenkinsUrl: "http://jenkins:8080"
          name: "kubernetes"
          namespace: {{ .Values.namespace }}
          skipTlsVerify: true
    credentials:
      system:
        domainCredentials:
        - credentials:
          - usernamePassword:
              description: "Githubuser"
              id: "some_randome"
              password: {{ .Values.credentials.github.password | quote }}
              scope: GLOBAL
              username: {{ .Values.credentials.github.username | quote }}
    unclassified:
      location:
        adminAddress: "puntiknikita@gmail.com"
        url: "http://{{ .Values.ingress.host }}/"
      shell:
        shell: "/bin/bash"
