---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-from-manifest
  namespace: default
spec:
  encryptedData:
    password: AgB+oYntmwgn2MwmtUwj3xYzvpX9j9hOlFwGAnou3ifhvgJwKLEEbLF5P9pp4TEj7rWbMKqC8Ke3qcQY2WVGs2NfXdpbpkfYY3r5vt3ywUAQc17Lnne549NRsoMDg0rvf3BqCymOauxWwJW8bMNFE+u8ksY1PGU9mP25b/z/Htv+kCbStfM4np+W9V8YkcpEU904clOfMktr63B2CJ6yWCcyqIVE65T8GyrFNDPWhaJBqOiGeBRsoMzkJlMSS9gGLO/hNHVznBG7nRpJ9iEBWY75GRAD8yRaJsTXTRDvewT/VNSMX0E4ZswY/nesqpk6xQfrjG91czDo8XyVVQgziG3X/omBxABP6GKkvnYqh3aEXnCPI7+cYLCpXqG8cQ3tzp8jBp577PTGxQHYA0sGDQTlnnds0St7IVz1lfFrH60xVj1K7tP7MBb6g85SLbLafPPTRqCwn6Jj72+leZUJeUrcpuFtJadOaI4EkA5Yax+eFyHrElVPIkHi+BZMHvaFjExdaehJ6pwdhGqH/JRdBO66B5I2TjwCsaN5ZT7QLTPVLBiUaKV8wfGQnMubP6XIglC0+QA2wfEf5quY8CunkCxsmtUdrIdC51aBAlVb9octGK6yCDXh3dtS2kyFTdBcUU4PHdzXtYqDbOqVV5/F7wcEjX30MTkh9W/w979RZNHEe+I5DHCPhJwQZ+5h3tgEr89uOwhQ
    user: AgAuKRmrqrgVq39ONxCqjgboXOorHjY2dM3uVWokjH0k4P7Rlp8Bhacea9eIDs/nJAX26wXbVK+qbUC+b3bcBGPd17cQHxBBGRRvkDS44SIDooXjcNezGtf49RhX8ImP8G8ObMSwFflCY1D5/IDd8UWQZKYwq4DR7lo7I9ghM+M+GHtkohR6fDfh5EpiW5cTUpc7lU9PzZD3VCFYOJ1pa+m9I/LR0NGs7ory/JeJzi+DwGAGb5Hggn8Ub1VNrmwKWAofhrKtZ3cN7dwbsZda3MdZQU3OpedmXEypgiJQ2gcg6AOrlYRjGnTrD3PdGeRCZN5O5M7mFMXrboR1X3GFQh1lH1z5c4iCerOFSJ/gro2O3D8j1W7WW1joSQUlFkpqunk+7KAP1e1CNC+sdxwbyWcTkv8DaJnE62FM4v81SGta+rPVvZ0CTQ7M+CTPZSruhvKDCEwO4u7qjcHLIt52VNcYeLhGxI1S7KyRBeUIDYBKyBVZx0n5rF26yA/K//WuvJHxums0xJkF6QKDfpfH4bMW+c2GF3uSN45hsBhOYy22YqWXVgbWYZgbtdxyax34xZ74Ty95THVt6VrsFws39pUXWXd6haKCDwAAH1uPhxQLbKcmpds/fgii8/OMtRhcjbx38HNyX2I8+Laj9OxKIUqRVYbGbqhM76HbR0elGFDSlY8Zjlcp0Dr9pNrj4JkyneWwMWBVXw==
  template:
    metadata:
      name: secret-from-manifest
      namespace: default
    type: Opaque
