Vagrant.configure("2") do |config|
    config.vm.define "debian-11" do |debian|
      debian.vm.box = "teak/bullseye64"
      debian.vm.network "private_network", ip: "192.168.161.131"
      debian.vm.provider "vmware_desktop" do |vmware|
         vmware.gui = false
         vmware.memory = "1024"
         vmware.cpus = "2"
      end
      debian.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y vim git wget curl nginx
        cp /vagrant/debian.html /var/www/html/index.html
        systemctl restart nginx
      SHELL
    end
    config.vm.define "centos-7" do |centos|
      centos.vm.box = "centos/7"
      centos.vm.network "private_network", ip: "192.168.161.130"
      centos.vm.provider "vmware_desktop" do |vmware|
		 vmware.vmx["ethernet0.pcislotnumber"] = "32"
         vmware.gui = false
         vmware.memory = "1024"
         vmware.cpus = "2"
      end
      centos.vm.provision "shell", inline: <<-SHELL
        yum update -y
		yum install -y vim git wget curl nginx
        cp /vagrant/centos.html /usr/share/nginx/html/index.html 
        systemctl enable nginx
        systemctl start nginx
      SHELL
    end
  end
  
