{
 "title": "logging",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "ArgoCD server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"argocd-server-58b85dcfcc-kkhx7\"} |= `error` [$time])"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-7578879f9f-f2lrx\"} |= `error` [$time])"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"node-exporter-xttdx\"} |= `error` [$time])"
    }
   ]
  },
  {
   "title": "Drupal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"drupal-7bd789d85d-5wjzc\"} |= `error` [$time])"
    }
   ]
  },
  {
   "title": "Jenkins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-helm-6c7dc95ff8-2492r\"} |= `error` [$time])"
    }
   ]
  }
 ]
}