Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.0.20", netmask:"255.255.255.0", bridge: "Intel(R) Ethernet Connection (7) I219-V"
    config.vm.provision :shell, :path => "ngnix.sh"
    config.vm.provision :shell, :path => "bootstrap.sh"
end