global:
  domain: "k8s-11.sa"
  
drupal:
  enabled: true
  persistence:
    enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/drupal
    tag: latest
  
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  resources:
    limits:
      memory: 1536Mi
    requests:
      memory: 512Mi    

  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: false
    image:
      registry: docker.io
      repository: bitnamilegacy/mariadb
      tag: latest
    auth:
      database: "bitnami_drupal"
      username: "bn_drupal"
      password: "password123"
      rootPassword: "password123"
  drupalUsername: "admin"
  drupalPassword: "password123"
  bitnamiDebug: true
  livenessProbe: {enabled: false}
  readinessProbe: {enabled: false}

wordpress:
  persistence:
    enabled: false
  wordpressUsername: "admin"
  wordpressPassword: "password123"
  mariadb:
    enabled: true
    fullnameOverride: "wp-db" 
    primary:
      persistence:
        enabled: false
    auth:
      existingSecret: ""
      database: "bitnami_wordpress"
      username: "bn_wordpress"
      password: "password123"
      rootPassword: "root-password"
  externalDatabase:
    existingSecret: ""  
    host: "wp-db" 
    user: "bn_wordpress"
    password: "password123"
    database: "bitnami_wordpress"
  ingress:
    enabled: false
  service:
    port: 80
    type: ClusterIP