$script = <<-SCRIPT
PUBLIC_MATER_KEY=“xxxxxxx”
yum -y install java git -q
useradd -d /bin/bash -d /var/lib/jenkins/ jenkins
runuser -l jenkins -c 'echo -e "\n\n\n" | ssh-keygen -t rsa'
echo $PUBLIC_MATER_KEY  > /var/lib/jenkins/.ssh/authorized_keys
chown jenkins:jenkins /var/lib/jenkins/.ssh/authorized_keys
chmod 600 /var/lib/jenkins/.ssh/authorized_keys
echo "Client done!"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins_node"
    config.vm.network "public_network", ip: "192.168.0.192",  bridge: "en0: Ethernet"
    config.vm.provision "shell",
        inline: $script
end

