Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.40" #,  bridge: "em1"
    config.vm.provision :shell, :path => "bootstrap.sh"
end