# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "first"
  config.vm.network "public_network", ip: "192.168.1.222", bridge: "em1"
  config.vm.provider "virtualbox" do |vb|
	vb.gui = false
	vb.memory = 1500 
 	vb.cpus = 1
  end 
  config.vm.provision :shell, :path => "run.sh"	
end
