name: Hello_action

on:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: python hello.py
