# Stage1
FROM golang:1.23.4-bookworm AS builder
WORKDIR /app
COPY Assignment_2/main.go .
RUN go build -o app main.go


#Stage2
FROM debian:bookworm-slim AS runtime
WORKDIR /app
COPY --from=builder /app/app .
EXPOSE 8080
CMD ["./app"]
