Vagrant.configure("2") do |config|
  
    #config.ssh.insert_key = false
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443
    config.vm.network "forwarded_port", guest: 8001, host: 8001
    config.vm.network "forwarded_port", guest: 30000, host: 30000
    config.vm.network "forwarded_port", guest: 35743, host: 35743
    config.vm.network "forwarded_port", guest: 35196, host: 35196
    
    if Vagrant.has_plugin?("vagrant-timezone")
      config.timezone.value = "Europe/Minsk"
    end
  
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
  
    config.vm.define "minikube" do |minikube|
      minikube.vm.box = "bento/ubuntu-16.04"
      minikube.vm.box_check_update = false
      minikube.vm.network "private_network", ip: "192.168.56.201"
      #minikube.vm.network "public_network", ip: "192.168.56.201",  bridge: "wlp4s0"
      minikube.vm.hostname = "minikube"
      #minikube.vm.provision "ansible_local" do |ansible|
      #  ansible.install_mode = "default"
      #  ansible.become = true
      #  #ansible.inventory_path = "./ansible/inventory.yml"
      #  ansible.playbook = "./ansible/minikube_playbook.yml"
      #  ansible.config_file = "./ansible/ansible.cfg"
     #end
    end

# sudo sysctl -w net.ipv4.ip_forward=1
end


