Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.0.246",  bridge: "wlo1"
    config.vm.provision "file", source: "~/sa/sa.it-academy.by/workin_dir/jenkins/nginx.conf", destination: "/tmp/nginx.conf"
    config.vm.provision "file", source: "~/sa/sa.it-academy.by/workin_dir/jenkins/jenkins.conf", destination: "/tmp/jenkins.conf"
    config.vm.provision :shell, :path => "bootstrap.sh"
end
