---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-from-manifest
  namespace: default
spec:
  encryptedData:
    password: AgCSKqqtxV5izxjrl9/NF1dVHZVncuYLHShTMA37vs77Wh8BQNw7EkNIsD56YBpJlTaX1eggRCP7CFMcfbYIc67p6J+RQynggiOR/FZr+bhJ5nz+Eji2mKC485WQcz4Ja/MksrBO1bvhKirRFyGLI/onMr6/7i5ZdHr4aIL87vGWi3v8LDjqtzS1o6Lq4VBbvdI2t+PAWbjDrl0onzhK7lEgKGVVK1mV5ctAP88GVCnsmZWbkw3j2BMd0HJqYLmKEnfuJvva6SZAXHyl1IiVfxzNMalLv83uq6Trh0iqGadRgAObGb+ZthF6JSysW6Gx7/lsNmY0lGV6KxRmhGcp79DVd53Wm81MRZ7hed5rLQchMc/txtWvzetHzCY6dWrzC3qYPYpGyIscizNEhgjJ7kf5bc/wrH6XjU5X8v76bT3W4txWFQ89cszz4Dn3TIFzKWIUGR3P0F1Grjfm3pIG9wUOPl8+bNESxgRr8zEqdq3vBGOPPqRuIrvugCX1OGq7DcWkYExoLPx0of2bF0LZ/+bGoRyP9iSfnzmO5JH2q21dHdoZCdPnFhvjh0jLog0c3VcstN2thWowHxCPvbMF4UOwswwiOFZAlE01LUX/mNYnIhdhXAY6a7s3slqR4yLbbnKFVsN4cB82/707KaQE6BAUs/toHP7uEmUVbUY1DeyMAchcFXGZJcp6VF2iTq9fgzIG+dfM
    user: AgBTe/pC3GxDFRWCmqvWi6MRQUGQNwZuyOPDOttNGZs0sqzbG061OizW+F7PQereJocIcvDr9IIh7Avzax0DPKY1z091csnbikH6IjQPQTMPlxLOVf7hHsXlgo0BLkz1jum9xZfypphdTE3m0NRJAvpTN8jSMk9dNvHjW8v/YQBZpT1UgJQuMBkWOmu7ewvRvv2Mr19UDevKynffCi5nMOAd1YgIE9KsDZJjD59e+1YyDIehJUZ5IOwikL7m6IHjGSDTkwU0WqOdz4/HukMGCSD2BA0qsKNWpbWwbhnBSWZLEUx3tGDVe29x+sYovJL+iZMRvmKNr0nd1GYZ80PaUSzmEE/GnzIWiFmVeU1LYXjKdWMfDRE7Op1fZMUVl4Q8bjmzxS/PIka/otjElM72sy7B3Pljdy8vpsLkjDQHtTu6ePsuqQ7XCHChq6Lfvr76IrzA/+BJCT14WA/RDc8Lf943RKsDWJC6pqRMJz1cSIRU+SzZ3BmX5g3fdFKLoo6UWUVMgVsMBWZS4N0LYoTJf9oCm6DL3kZdMkjDdJa29wAvpkgzKNzjR/IqyBv1NWJHCU8fhxcHN8Yroo14/aVYYaJAvhPhS9wYXS5lP1XzNIz99y9yByRjyUCWoxtV/6B5gJv622s5sPFdrLa2Qd2dTL0uCzgkMRP7Wdxgdp4VCz/GDnQFBxyw3lpZVVlIJL19opta2Ph8gA==
  template:
    metadata:
      name: secret-from-manifest
      namespace: default
    type: Opaque
