

Vagrant.configure("2") do |config|
  config.vm.define "host1" do |debian|
    debian.vm.box = "bento/debian-10"
    debian.vm.network "forwarded_port", guest: 22, host: 2226
    debian.vm.network "private_network", ip: "10.1.1.11"
    debian.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "1024"
       vb.name = "debian10"
    end
    debian.vm.provision "shell", inline: <<-SHELL
      adduser updater -p vagrant
      echo "updater ALL=(ALL:ALL) NOPASSWD: ALL:" >> /etc/sudoers 
      apt install -y vim git wget curl
    SHELL
  end
  config.vm.define "host2" do |centos|
    centos.vm.box = "generic/centos8"
    centos.vm.network "forwarded_port", guest: 22, host: 2227
    centos.vm.network "private_network", ip: "10.1.1.12"
    centos.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "1024"
       vb.name = "centos8"
    end
    centos.vm.provision "shell", inline: <<-SHELL
      adduser updater -p vagrant
      echo 'updater   ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
      dnf install git wget curl vim -y
    SHELL
  end
end 

