---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-from-manifest
  namespace: default
spec:
  encryptedData:
    password: AgB9IYR76/mfMHSVlHuke6QBICHb0G3eLTdAopgOqevFcm5NTDasrFs/pkwg55XheUBk/HVkbnaRo9LRFOnjlDLxwmwe7WHBlR//LlhqLbz03/RbHmM2oekfLgsc4UqMu4GAYvuW9nYfXP5R2TcWyXDD/TSlVSzZyRFCJBFIHD5V43eCEQu62PJwiWj4RpJ94m0E7g/YrNAS25MqflW3DKjj5yxpKtajwrGFJMOpaNkAy/MjuQwm15sR8Y3H+XTeBUXGmBeNk/YF6lNIVdR7CMovPOgKoAkJ4KeXXERxg4t8Lo8/eXYzXW8afkSZQAOXBcfNonKSOalwhbhuadfEPULaYpraefk/dy7KmwPHI1RweT7AwCTRYk8PVYpyrzBnikESQtylynFKb5txebxnkyEJOyu0y3dAt+3BJV6mq6HLTHkvlIGCj9NeBKewIDiwDX0i10DlRu7X8GeQQWzNdxxDiw4XOkqm+9/2F6S7+/Vt1UvMUhy9waNMOjGWj+/lbOzbj4ENQtb2FUPg331mR1cAvX4I/oWt7TGnj92XIiplenrHjTt4jCSSMP5koZG3Tg7cZY6zX+aJIO5gqpfOi8yjabn74zMNzVpctux+xzyU20e3WXob9l5+wYbZokerukIfQyyhN/G2COW2isE+ZoeMvBFOLQXKjSAVIPbWg1T8lnYa4hH1yXYmqRmHgqNHBMQjTKBb
    user: AgBmIv6MBZZIoIpOJA+/7yFmNmaC5CVQ5F+9j9j30GjTe9GsKYNSSt7eHweuxEgh5ysyM1MAc24JEzC8CECUXGxEWKL8Q+szoTGAI/BKA3TS014NIM/p0xKUqJpfPOqULN4TU1nrGjdQffOVJticLpJbonEf340H7hDTfweof7RU3kSSbJuqQdS2AQMkXeez1ffRay5Cdnn4iiC4fTwRvHbIot7JzIprVGJF+okPHim1EXUnHhrHOJMo3ZnlkHpFuIEjac52lpQvs3MGX5ggzhgQ/hfSdOGqIZJPaSKBtyYggZ1amWWvQJOGmBnnH1c1uHe2FtV9t5PcS1gjBhWRgersj1N9/Cp7PMMfurBDeExrgktaAIgPhPEiRRw0ilVi/R6Df0uHMuuNWWYYNGNcU/uZeumde/zlZNr3tyLGKitgtdgl1GEyq6WsUiMd0ylNs9nhBNSwpNjR8/NBwd+riNs85TehSdsP8yXaOQuzGKPrIL/A3lHDwvUq8MHbnhs+IqFXyv2gm/WTn3JIZ2NtawxJLcJ1A/Oy7xEAqZctHWvcRaycPl3bl8ff7Qt7+Rgl5UmkZFiBBBei9ySCkhL+zWgPfw0KACXM9mJjmkSggyrG2A/ZLDvS4+t5vfr2nu34ZzQW3pCBsECZ5yGO6xdlLupvwN4AXAtUCYjT8niVMkFSrOA49vz6SdZxFZHoawvW5loovb9KCQ==
  template:
    metadata:
      name: secret-from-manifest
      namespace: default
    type: Opaque
