apiVersion: apps/v1 # версия API Kubernetes
kind: Deployment # тип создаваемого объекта
metadata:
  name: nginx-deployment # уникальное имя деплоймента в кластере
  labels:
    app: nginx # метка (тег) самого деплоймента для удобства поиска
spec:
  replicas: 4 # инструкция кластеру всегда поддерживать ровно 4 запущенных пода с Nginx
  strategy:
    type: RollingUpdate #  стратегия «плавной» замены старых подов на новые при обновлении приложения (без полной остановки сервиса)
    rollingUpdate:
      maxSurge: 1       # во время обновления кластер может создать максимум на 1 под больше, чем задано в replicas (то есть временно будет 5 подов)
      maxUnavailable: 0 # в процессе обновления 0 подов могут быть недоступны. Кластер не удалит ни один старый под, пока не запустится и не станет полностью готовым новый. Это гарантирует круглосуточную доступность
  selector:
    matchLabels:
      app: nginx # указывает деплойменту, какими именно подами он должен управлять (он ищет поды с меткой app: nginx)
  template: # шаблон, по которому будут создаваться новые поды
    metadata:
      labels:
        app: nginx # метка, которая присваивается каждому созданному поду (важно для селекторов сервиса и деплоймента)
    spec:
      containers: # список контейнеров внутри пода
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80 # порт, который сетевой плагин открывает внутри самого контейнера Nginx
          # Запросы и лимиты ресурсов для подов
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          # Проверки готовности, чтобы трафик не шел на незапущенные поды
          readinessProbe: # проверка готовности пода принимать трафик. Если веб-страница по пути / на порту 80 возвращает успешный код (200-399), под включается в балансировку. initialDelaySeconds: 3 (подождать 3 секунды после старта перед первой проверкой), periodSeconds: 5 (проверять каждые 5 секунд).
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # проверка, что контейнер «жив». Если Nginx намертво зависнет и перестанет отвечать на порту 80, Kubernetes автоматически перезапустит этот конкретный контейнер
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
