apiVersion: networking.istio.io/v1alpha3 # версия API, используемая сервис-мешем Istio
kind: Gateway # тип объекта Istio, отвечающий за конфигурацию портов на внешнем контуре
metadata:
  name: nginx-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # указывает, к какому именно физическому поду-шлюзу применить эту настройку
  servers: # описание правил приема трафика
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "nginx-test.k8s-1.sa"
        - "nginx-test.k8s-2.sa"
