apiVersion: v1
kind: Service # тип объекта — сетевая служба (сервис)
metadata:
  name: nginx-service # имя сервиса, по которому к нему будут обращаться другие компоненты (включая Istio)
spec:
  selector:
    app: nginx # ищет в кластере любые поды с меткой app: nginx и начинает балансировать трафик между ними
  ports:
    - protocol: TCP # протокол передачи данных
      port: 80
      targetPort: 80
  type: ClusterIP  # тип сервиса «только внутри кластера». Он не имеет внешнего IP-адреса, так как за внешнюю доступность у нас отвечает Istio
