apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: default
  labels:
    app: shell
spec:
  containers:
  - name: shell
    image: alpine:3.18
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]