Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.0.110",  bridge: "wlp2s0"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "play.yaml"
    end
end
