Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.100.10",  bridge: "enp1s0" ## TO CHANGE
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "play.yaml"
      ansible.install_mode = "pip"
      ansible.version = "2.10.3"
    end
end

