Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"


  config.vm.network "public_network", ip: "192.168.100.143"

  config.vm.hostname = "jenkins"
  config.vm.provision "file", source: "proxy.txt", destination: "/tmp/jenkins_nginx.conf"

  config.vm.provision :shell, :path => "bootstrap.txt"


   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     vb.memory = "1024"
     vb.cpus = "2"

   end

end
