{
 "title": "17. Monitoring. Log HW",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "alertmanager",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"alertmanager-58fc6c868f-56tb6\"} |= \"error\" [$time])"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-7578879f9f-ncm5q\"} |= \"error\" [$time])"
    }
   ]
  },
  {
   "title": "jenkins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-57f664d6bd-nxgft\"} |= \"error\" [$time])"
    }
   ]
  }
 ]
}