Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "Jenkins"
    config.vm.network "public_network", ip: "192.168.1.211",  bridge: "wlp3s0"
    config.vm.provision "file", source: "~/Jenkins/10.Jenkins.Start/jenkins_nginx.conf", destination: "/tmp/jenkins_nginx.conf"
    config.vm.provision :shell, :path => "bootstrap.sh"  
end
