Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "public_network", ip: "192.168.100.10", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |v|
	v.memory = 512
    v.cpus = 1
  end
  
  config.vm.provision "shell", path: "run.sh"
  
end
