name: run-script

on:
  push:
    branches: 
    -  master

jobs:
  run-hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout 
      uses: actions/checkout@v4
      
    - name: run script
      run: python Volha_Zhukova/04.GitOps/hello.py