apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-db
  namespace: vso-demo
spec:
  type: kv-v2
  mount: secret
  path: app/db
  refreshAfter: 30s
  vaultAuthRef: vault-auth
  destination:
    name: app-db
    create: true
