{
 "title": "16. Log monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "label": "time period", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Drupal, Wordpress errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"drupal\", app=\"drupal\"} [$time] !~\"1.1\\\" 200\"))",
     "legendFormat": "Error count Drupal"
    },
    {
     "expr": "sum(rate({namespace=\"wordpress\", app=\"wordpress\", container=\"wordpress\"} [$time] !~\"1.1\\\" 200\"))",
     "legendFormat": "Error count Wordpress"
    }
   ]
  },
  {
   "title": "Node exporter errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({app=~\"node1\"} [$time] |= \"error\"))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Ingress and Jenkins errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"ingress.*\"}[$time] |~ \"ERR\")",
     "legendFormat": "Ingree errors"
    },
    {
     "expr": "count_over_time({pod=~\"jenkins.*\"} [$time] |~\"ERROR\")",
     "legendFormat": "Jeknkins errors"
    }
   ]
  }
 ]
}