pipeline {
  environment {
    registry = "sliaptsou/13_docker_lading"
    registryCredential = 'dockerhub'
  }
  agent { label '113-debian'}
  stages {
    stage('Cloning Git') {
      steps {
        git 'git@github.com:sliaptsou/13_docker_lading.git'
      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Push image') {
      steps{
        script {
          docker.withRegistry('', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }
}
