$masterSetup = <<-SCRIPT
echo "##### app installation"

yum check-update
yum -y install nano
sudo yum -y install epel-release
sudo yum -y install nginx
sudo systemctl start nginx
sudo systemctl enable nginx

echo "##### jenkins preparation"

yum install java wget git -y --nogpgcheck -q
wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
yum install jenkins -y --nogpgcheck -q
usermod -s /bin/bash jenkins
systemctl enable jenkins
systemctl start jenkins

echo "##### Waiting for secret"

while [ ! -f /var/lib/jenkins/secrets/initialAdminPassword ]
do
    sleep 2
done

echo "##### ssh preparation"

cat /tmp/pub_key.pub >> /home/vagrant/.ssh/authorized_keys
chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
chmod 600 /home/vagrant/.ssh/authorized_keys

echo "##### Secret here"
cat /var/lib/jenkins/secrets/initialAdminPassword
SCRIPT


PUB_KEY_PATH = "~/.ssh/id_rsa.pub"


MACHINES = {
  'master'  =>  { vcpu: '1', ram: '1024', ip: '10.20.30.40'},
}


INSTANCES = MACHINES.flat_map do |server_name, server|
    server.merge({
      :vagrant_name => "#{server_name}",
    })
end


Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  INSTANCES.each do |instance|
    config.vm.define instance[:vagrant_name] do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = instance[:vagrant_name]
      node.vm.network "private_network", ip: instance[:ip]


      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = instance[:ram]
        vb.cpus = instance[:vcpu]
      end


      node.vm.provision "file", source: PUB_KEY_PATH, destination: "/tmp/pub_key.pub"


      if instance[:vagrant_name] == "master"
        node.vm.network "public_network", ip: "192.168.55.80", bridge: "enp3s0"
        node.vm.provision "shell", inline: $masterSetup
      end


    end
  end
end
