{
 "title": "Dashbord 16 HW",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "time", "label": "time", "query": "5m , 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "node-exporter : error $time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"node-exporter-sslsn\"} |= `error` [$time])"
    }
   ]
  },
  {
   "title": "Jenkins : INFO $time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"jenkins-helm-dc97798b9-2djgq\"} |= `INFO` [$time])"
    }
   ]
  },
  {
   "title": "Drupal : GET $time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"sa-drupal-68474c869f-5xz5q\"} |= `GET` [$time])"
    }
   ]
  },
  {
   "title": "Ingress : 400 $time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"ingress-nginx-controller-7578879f9f-fhcmz\"} |= `400` [$time])"
    }
   ]
  },
  {
   "title": "Wordpress : GET $time",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time({pod=\"sa-wordpress-c677cd6cd-dbwsd\"} |= `GET` [$time])"
    }
   ]
  }
 ]
}