all:
  children:
    linux:
      hosts:
        PC_26: 
          ansible_host: 192.168.12.26
          ansible_port: 22
          ansible_user: tor
          new_hostname: debian26
          new_fqdn: debian26.internal
        PC_27: 
          ansible_host: 192.168.12.27
          ansible_port: 22
          ansible_user: tor
          new_hostname: debian27
          new_fqdn: debian27.internal